[workspace]
members = [ 
    "ic-http",
    "examples/todo_server",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Long Tran <tranbaolong14@gmail.com>"]
license = "MIT"
